#:import settings settings

<Sprite>:
    size_hint: None, None
    size: app.tilesize, app.tilesize
    tile: 0, 0
    x: app.tilesize * self.tile[0]
    y: app.tilesize * self.tile[1]

<Platform>:
    color: settings.COLORS.get("brown")

<Rock>:
    color: settings.COLORS.get("darkbrown")

<Game>:
    Label:
        text: "fps: %s" % int(root.fps)
        size_hint: None, None
        x: app.width / 2
        top: app.height