
name: Platform
tilesize: 64
background:
    color: darkblue
screen:
    width: 800
    height: 480
    fps: 60

gravity: 100
air_resistence: -5
meter: 50  # meters to pixels

player:
    layer: 2
    color: yellow
    width: 30
    height: 50
    weight: 500
    mass: 75
    pos:
        x: 450
        y: 50
    speed:
        walk: 300
        running: 00
    aceleration: 5000
    jump: 2000
    friction: 10

ground:
    layer: 1
    height: 50
    width: 3000
    color: brown
    friction: 5

rocks:
    layer: 1
    color: grey
    density: 10
    coefficient of friction:
        static: 5
        kinetic: 3
    rock1:
        width: 300
        height: 250
        pos:
            x: 1000
            y: 50
    rock2:
        width: 300
        height: 30
        pos:
            x: 350
            y: 250
    rock3:
        width: 230
        height: 30
        pos:
            x: 50
            y: 50


boxes:
    layer: 1
    density: 1
    coefficient of friction:
        static: .5
        kinetic: .3
    box1:
        color: (139,69,19)
        width: 60
        height: 70
        pos:
            x: 660
            y: 50
