
name: Platform
tilesize: 64
background:
    color: darkblue
screen:
    width: 800
    height: 480
    fps: 60

gravity: 100
air_resistence: -2
meter: 50  # meters to pixels

player:
    layer: 2
    color: yellow
    width: 30
    height: 50
    weight: 500
    mass: 75
    pos:
        x: 700
        y: 50
    speed:
        walk: 300
        running: 00
    aceleration: 5000
    jump: 2500
    coefficient of friction:
        static: 5
        kinetic: 3

ground:
    layer: 1
    height: 50
    width: 5000
    color: brown
    coefficient of friction:
        static: 5
        kinetic: 3

rocks:
    layer: 1
    color: grey
    density: 3
    coefficient of friction:
        static: 5
        kinetic: 3
    rock1:
        width: 300
        height: 250
        pos:
            x: 2000
            y: 50
    rock2:
        width: 300
        height: 30
        pos:
            x: 1450
            y: 250
    rock3:
        width: 230
        height: 30
        pos:
            x: 150
            y: 50


boxes:
    layer: 1
    density: 1
    color: (139,69,19)
    coefficient of friction:
        static: .5
        kinetic: .3
    box1:
        width: 60
        height: 70
        pos:
            x: 560
            y: 50
    box2:
        width: 60
        height: 70
        pos:
            x: 460
            y: 50
    box3:
        width: 60
        height: 70
        pos:
            x: 360
            y: 50
